### ISSUE TITLE
Delayed Jobs

### ISSUE THREAD

**Issue by logicalparadox** [qualiancy/kinetik#1]
All for jobs to be delays using parseable timestamps.

``` js
job.create('email', {
// ...
}, 300); 
```

**Comment by pgherveou** [comment]
add possibility to cancel job too

**Comment by logicalparadox** [comment]
Delayed jobs finished. Follow #3 for job cancellation.

Until documentation is updated, the following format is supported:

``` js
job.create('email'. {
// data object to send
}, 300); // number of milliseconds to delay.
```

Later version will support smart time parsing such as '2m', '3d'.
