### ISSUE TITLE
log format

### ISSUE THREAD

**Issue by pgherveou** [qualiancy/kinetik#13]
running kinetik with debug flag it output something like that 

```
  kinetik:processor found job email_confirm +0ms
  kinetik:processor processing email_confirm +13ms
  kinetik:processor task Job has started processing log: %s +2ms   **
  kinetik:processor task Job has failed: "undefined" log: %s +45s    **
  kinetik:processor task email_confirm failed for job 323771329597440 +9ms
```

looks liike something is wrong with the log formatting

**Comment by logicalparadox** [comment]
There are two things going on here. One is logging for the actual process. The other is the logging for the logging for the "logger". I will clean this up with the next patch release.
