### ISSUE TITLE
not picking up jobs 

### ISSUE THREAD

**Issue by pgherveou** [qualiancy/kinetik#7]
Jake i don't have test for that but I noticed that if 
- you flush redis
- start your job process 
- insert a job

kinetik wont pickup the job. if I restart the job process it will pickup and execute the job

**Comment by logicalparadox** [comment]
How long are you waiting? I added an option to the settings called `interval` ... which defaults to 10 seconds ... https://github.com/qualiancy/kinetik/blob/master/lib/kinetik/queue.js#L47

It used to be 500ms so they could be the delay your seeing. If that isn't it, let me know. This could interest you: https://github.com/qualiancy/kinetik/blob/master/test/queue.js#L22

**Comment by pgherveou** [comment]
It looks like nothing is triggered until I restart the script, 
this only happen when redis is initially empty then job script start and messages come in.
let me double check that and come back to you

**Comment by logicalparadox** [comment]
I was able to duplicate this using the `examples/processes`. Will work on a fix this evening.

**Comment by logicalparadox** [comment]
This was a bug in dependency seed-redis. Was fixed in seed-redis@0.4.1.

Please update kinetik to 0.0.11 to support the minor version change in the dependancies.

Let me know if you have further issues.
